### PR TITLE
Added Hello Screens consolidation alerts documentation

### PR DESCRIPTION
**Pull request by toroduque**

### CODE REVIEW

**Comment by stewartcollins7** [comment]
Looks good but there's no mention of store level consolidation alerts, should this be added?

**Comment by toroduque** [comment]
@stewartcollins7 Great point. Updated!

**Comment by stewartcollins7** [comment]
another thing is that this is not currently enabled by default and i have not added it to the hello default states at present. the only way for it to be enabled is by a bluedot team member enabling state templates or setting the custom configuration. do you want me to make this enabled by default or do you just want to add a line here saying "Contact bluedot staff if you want to enable this feature: or something

**Review by stewartcollins7 — APPROVED** [review]
looks good

**Pull request merged**
